import type { EnvVar, ModuleManifest } from "../schema/manifest";

export const ENV_EXAMPLE_HEADER = `# Generated by site-forge from module manifests. Copy to .env.local and fill in.
# Variables marked (required) must be set in production; in development every
# module falls back to a safe local behavior when they are missing.`;

function block(title: string, vars: EnvVar[], seen: Set<string>) {
  const lines: string[] = [];
  for (const variable of vars) {
    if (seen.has(variable.name)) continue;
    seen.add(variable.name);
    lines.push(`# ${variable.description}${variable.required ? " (required)" : ""}`);
    if (variable.howTo) lines.push(`# → ${variable.howTo}`);
    lines.push(`${variable.name}=${variable.example}`);
  }
  if (lines.length === 0) return null;
  return `# ─── ${title} ${"─".repeat(Math.max(3, 70 - title.length))}\n${lines.join("\n")}`;
}

export function generateEnvExample(coreEnv: EnvVar[], modules: ModuleManifest[]) {
  const seen = new Set<string>();
  const blocks = [
    block("core", coreEnv, seen),
    ...modules.map((m) => block(m.name, m.env, seen)),
  ].filter(Boolean);
  return `${ENV_EXAMPLE_HEADER}\n\n${blocks.join("\n\n")}\n`;
}
