import path from "node:path";

import type {
  CoreManifest,
  ModuleManifest,
  SlotContribution,
  SlotDefinition,
} from "../schema/manifest";
import { toPosix } from "../utils/fs";
import { camelCase } from "../utils/strings";

export const GENERATED_HEADER =
  "// @generated by site-forge — do not edit. Run `pnpm site sync` to regenerate.";

export type GeneratedFiles = {
  /** Files to write, keyed by project-relative path. */
  write: Map<string, string>;
  /** Generated files that must be deleted if present (e.g. src/proxy.ts with no handlers). */
  remove: string[];
};

/** Import specifier from one project file to another, without extension. */
export function relativeImport(fromFile: string, toFile: string) {
  const withoutExt = toFile.replace(/\.(tsx?|jsx?|mts)$/, "");
  let specifier = toPosix(path.posix.relative(path.posix.dirname(fromFile), withoutExt));
  if (!specifier.startsWith(".")) specifier = `./${specifier}`;
  return specifier;
}

function arrayType(type: string) {
  return /=>|\||&/.test(type) ? `(${type})[]` : `${type}[]`;
}

export function envExportName(moduleName: string) {
  return `${camelCase(moduleName)}Env`;
}

type Contribution = SlotContribution & { module: string; index: number };

function collectContributions(modules: ModuleManifest[]) {
  const bySlot = new Map<string, Contribution[]>();
  modules.forEach((manifest, index) => {
    for (const contribution of manifest.contributes.slots) {
      const list = bySlot.get(contribution.slot) ?? [];
      list.push({ ...contribution, module: manifest.name, index });
      bySlot.set(contribution.slot, list);
    }
  });
  for (const list of bySlot.values()) list.sort((a, b) => a.order - b.order || a.index - b.index);
  return bySlot;
}

/** Imports with unique local names (aliased when two modules export the same name). */
function importLines(file: string, contributions: Contribution[]) {
  const used = new Set<string>();
  const locals: string[] = [];
  const lines: string[] = [];
  for (const contribution of contributions) {
    let local = contribution.import;
    let n = 2;
    while (used.has(local)) local = `${contribution.import}${n++}`;
    used.add(local);
    locals.push(local);
    const binding = local === contribution.import ? local : `${contribution.import} as ${local}`;
    lines.push(`import { ${binding} } from "${relativeImport(file, contribution.from)}";`);
  }
  return { lines, locals };
}

function listSlotFile(definition: SlotDefinition, contributions: Contribution[]) {
  const { lines, locals } = importLines(definition.file, contributions);
  const out = [GENERATED_HEADER];
  if (definition.typeImports.length > 0) out.push(...definition.typeImports);
  if (lines.length > 0) {
    if (definition.typeImports.length > 0) out.push("");
    out.push(...lines);
  }
  out.push("");
  out.push(`/** ${definition.description} */`);
  const value = locals.length === 0 ? "[]" : `[\n${locals.map((l) => `  ${l},`).join("\n")}\n]`;
  out.push(`export const ${definition.export}: ${arrayType(definition.type)} = ${value};`);
  return `${out.join("\n")}\n`;
}

function modulesFile(modules: ModuleManifest[]) {
  const names = modules.map((m) => `"${m.name}"`);
  const value = names.length === 0 ? "[]" : `[\n${names.map((n) => `  ${n},`).join("\n")}\n]`;
  return `${GENERATED_HEADER}

/** Modules installed in this site, in dependency order. */
export const installedModules = ${value} as const satisfies readonly string[];

export type InstalledModule = (typeof installedModules)[number];
`;
}

function envFile(modules: ModuleManifest[]) {
  const withEnv = modules.filter((m) => m.envFile);
  const imports = [
    `import { coreEnv } from "./env/core";`,
    ...withEnv.map(
      (m) =>
        `import { ${envExportName(m.name)} } from "${relativeImport("src/env.ts", m.envFile!)}";`,
    ),
  ].sort();
  const names = ["coreEnv", ...withEnv.map((m) => envExportName(m.name))];
  const extendsValue =
    names.length <= 3 ? `[${names.join(", ")}]` : `[\n    ${names.join(",\n    ")},\n  ]`;
  return `${GENERATED_HEADER}
// Add variables to a fragment in src/env/ instead; each module owns one.
import { createEnv } from "@t3-oss/env-nextjs";

${imports.join("\n")}

export const env = createEnv({
  extends: ${extendsValue},
  server: {},
  client: {},
  experimental__runtimeEnv: {},
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
`;
}

function mergeNext(modules: ModuleManifest[]) {
  const serverExternalPackages = new Set<string>();
  const imageRemotePatterns = new Map<string, unknown>();
  const csp: Record<string, Set<string>> = {};
  for (const { contributes } of modules) {
    contributes.next.serverExternalPackages.forEach((pkg) => serverExternalPackages.add(pkg));
    for (const pattern of contributes.next.imageRemotePatterns) {
      imageRemotePatterns.set(JSON.stringify(pattern), pattern);
    }
    for (const [directive, sources] of Object.entries(contributes.next.csp)) {
      csp[directive] ??= new Set();
      sources.forEach((source) => csp[directive]!.add(source));
    }
  }
  return {
    serverExternalPackages: [...serverExternalPackages].sort(),
    imageRemotePatterns: [...imageRemotePatterns.values()],
    csp: Object.fromEntries(
      Object.entries(csp).map(([directive, set]) => [directive, [...set].sort()]),
    ),
  };
}

function literal(value: unknown, indent: string) {
  const json = JSON.stringify(value, null, 2);
  return json.split("\n").join(`\n${indent}`);
}

function nextFile(modules: ModuleManifest[], plugins: Contribution[]) {
  const file = "src/generated/next.ts";
  const { lines, locals } = importLines(file, plugins);
  const merged = mergeNext(modules);
  const pluginList = locals.length === 0 ? "[]" : `[${locals.join(", ")}]`;
  const packages = merged.serverExternalPackages.length
    ? literal(merged.serverExternalPackages, "  ")
    : "[]";
  const patterns = merged.imageRemotePatterns.length
    ? literal(merged.imageRemotePatterns, "  ")
    : "[]";
  const csp = Object.keys(merged.csp).length ? literal(merged.csp, "  ") : "{}";
  return `${GENERATED_HEADER}
import type { NextConfig } from "next";
${lines.length ? `\n${lines.join("\n")}\n` : ""}
type NextPlugin = (config: NextConfig) => NextConfig;

/** next.config wrappers contributed by modules, applied in order. */
export const nextPlugins: NextPlugin[] = ${pluginList};

/** Config fragments contributed by modules. */
export const moduleNextConfig = {
  serverExternalPackages: ${packages} as string[],
  imageRemotePatterns: ${patterns} as { protocol?: "http" | "https"; hostname: string; pathname?: string }[],
  csp: ${csp} as Record<string, string[]>,
};
`;
}

function dbSchemaFile(modules: ModuleManifest[]) {
  const file = "src/generated/db-schema.ts";
  const lines = modules.flatMap((m) =>
    m.dbSchema.map((schema) => `export * from "${relativeImport(file, schema)}";`),
  );
  return `${GENERATED_HEADER}
// Every Drizzle table from installed modules. Relative imports keep drizzle-kit happy.
${lines.length ? lines.join("\n") : "export {};"}
`;
}

const PROXY_FILE = `${GENERATED_HEADER}
import type { NextRequest } from "next/server";

import { proxyHandlers } from "./generated/proxy";

/** Runs module proxy handlers in order; the first one that returns a response wins. */
export async function proxy(request: NextRequest) {
  for (const handler of proxyHandlers) {
    const response = await handler(request);
    if (response) return response;
  }
}

export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|.*\\\\.(?:svg|png|jpg|jpeg|gif|webp|avif|ico|txt|xml|woff2?)$).*)",
  ],
};
`;

/** Computes every CLI-owned file for a set of installed modules. */
export function generateFiles(
  core: Pick<CoreManifest, "slots">,
  modules: ModuleManifest[],
): GeneratedFiles {
  const write = new Map<string, string>();
  const remove: string[] = [];
  const contributions = collectContributions(modules);

  const slots = new Map<string, SlotDefinition>(Object.entries(core.slots));
  for (const manifest of modules) {
    for (const [slotName, definition] of Object.entries(manifest.slots))
      slots.set(slotName, definition);
  }

  for (const [slotName, definition] of slots) {
    if (slotName === "next-plugins") continue;
    // Contributions to slots whose owner isn't installed are skipped on purpose.
    write.set(definition.file, listSlotFile(definition, contributions.get(slotName) ?? []));
  }

  write.set("src/generated/modules.ts", modulesFile(modules));
  write.set("src/env.ts", envFile(modules));
  write.set("src/generated/next.ts", nextFile(modules, contributions.get("next-plugins") ?? []));

  if (modules.some((m) => m.dbSchema.length > 0 || m.name === "database")) {
    write.set("src/generated/db-schema.ts", dbSchemaFile(modules));
  } else {
    remove.push("src/generated/db-schema.ts");
  }

  if ((contributions.get("proxy") ?? []).length > 0) {
    write.set("src/proxy.ts", PROXY_FILE);
  } else {
    remove.push("src/proxy.ts");
  }

  return { write, remove };
}
