import { readdir } from "node:fs/promises";
import path from "node:path";

import { describeChanges, updateSiteConfig, type SiteConfigChanges } from "../codemods/site-config";
import { generateEnvExample } from "../generate/env-example";
import { generateFiles } from "../generate/generated-files";
import { updateReadme } from "../generate/readme";
import type { ItemKind, Registry } from "../registry/registry";
import type { Plan, Selection } from "../resolve";
import type { FileEntry, ModuleManifest, Preset, ProjectManifest } from "../schema/manifest";
import { CliError } from "../utils/errors";
import {
  exists,
  readBytesIfExists,
  readTextIfExists,
  remove,
  sha256,
  writeBytes,
  writeText,
} from "../utils/fs";
import { log } from "../utils/log";
import { mergePackageJson } from "./package-json";
import { readPackageJson, writeManifest, writePackageJson } from "./project";

export type ApplyResult = {
  written: string[];
  skipped: { path: string; reason: string }[];
  dependencies: string[];
  touched: string[];
  postInstall: { module: string; notes: string[] }[];
};

type CopyJob = {
  kind: ItemKind | "preset";
  name: string;
  entry: FileEntry;
  owner: string;
  force: boolean;
};

function itemJobs(registry: Registry, plan: Plan, selection: Selection, preset: Preset | null) {
  const jobs: CopyJob[] = [];
  const pick = <T extends { name: string; files: FileEntry[] }>(
    kind: ItemKind,
    list: T[],
    names: string[],
  ) => {
    for (const item of list.filter((i) => names.includes(i.name))) {
      for (const entry of item.files)
        jobs.push({ kind, name: item.name, entry, owner: `${kind}:${item.name}`, force: false });
    }
  };
  pick("ui", plan.ui, selection.ui);
  pick("section", plan.sections, selection.sections);
  pick("module", plan.modules, selection.modules);
  // Preset pages replace starter pages (e.g. the home page), so they overwrite.
  for (const entry of preset?.files ?? []) {
    jobs.push({
      kind: "preset",
      name: preset!.name,
      entry,
      owner: `preset:${preset!.name}`,
      force: true,
    });
  }
  return jobs;
}

/** Copies a registry file, refusing to clobber local edits unless forced. */
async function copyFile(
  registry: Registry,
  projectDir: string,
  manifest: ProjectManifest,
  job: CopyJob,
  overwrite: boolean,
) {
  const source = registry.filePath(job.kind, job.name, job.entry.from);
  if (!(await exists(source))) {
    throw new CliError(`Registry file missing: ${path.relative(registry.root, source)}`);
  }
  const content = (await readBytesIfExists(source))!;
  const hash = sha256(content);
  const destination = path.join(projectDir, job.entry.to);
  const current = await readBytesIfExists(destination);
  const same = current !== null && current.equals(content);

  if (current !== null && !same) {
    const tracked = manifest.files[job.entry.to];
    const untouched = tracked && tracked.hash === sha256(current);
    if (!overwrite && !job.force && !untouched) {
      return {
        status: "skipped" as const,
        reason: "exists with local changes (use --overwrite to replace)",
      };
    }
  }

  if (!same) await writeBytes(destination, content);
  manifest.files[job.entry.to] = { owner: job.owner, hash };
  return { status: same ? ("unchanged" as const) : ("written" as const) };
}

/** Rewrites every CLI-owned file (slots, env, .env.example) from the installed modules. */
export async function syncGenerated(projectDir: string, manifest: ProjectManifest) {
  const modules = orderedModules(manifest);
  const schemaDir = path.join(projectDir, "src", "db", "schema");
  const extraSchemaFiles = (await readdir(schemaDir).catch(() => [] as string[]))
    .filter((file) => file.endsWith(".ts"))
    .map((file) => `src/db/schema/${file}`);
  const generated = generateFiles(manifest.core, modules, { extraSchemaFiles });
  const changed: string[] = [];
  for (const [file, content] of generated.write) {
    const destination = path.join(projectDir, file);
    if ((await readTextIfExists(destination)) !== content) {
      await writeText(destination, content);
      changed.push(file);
    }
  }
  for (const file of generated.remove) {
    const destination = path.join(projectDir, file);
    const current = await readTextIfExists(destination);
    if (current?.startsWith("// @generated by site-forge")) {
      await remove(destination);
      changed.push(file);
    }
  }
  const workspaceFile = path.join(projectDir, "pnpm-workspace.yaml");
  const workspace = await readTextIfExists(workspaceFile);
  if (workspace?.startsWith(PNPM_WORKSPACE_HEADER)) {
    const next = pnpmWorkspace([
      ...manifest.core.allowBuilds,
      ...modules.flatMap((m) => m.contributes.allowBuilds),
    ]);
    if (next !== workspace) {
      await writeText(workspaceFile, next);
      changed.push("pnpm-workspace.yaml");
    }
  }
  const envExample = generateEnvExample(manifest.core.env, modules);
  if ((await readTextIfExists(path.join(projectDir, ".env.example"))) !== envExample) {
    await writeText(path.join(projectDir, ".env.example"), envExample);
    changed.push(".env.example");
  }
  return changed;
}

export const PNPM_WORKSPACE_HEADER = "# @generated by site-forge";

/** pnpm settings: packages allowed to run install scripts (pnpm ≥11 and ≤10 syntax). */
/**
 * pnpm refuses to install when a dependency's build script is neither allowed nor
 * denied, so every entry is explicit: "name" allows it, "!name" denies it
 * (optional native helpers with prebuilt fallbacks). Allowing wins over denying.
 */
export function pnpmWorkspace(packages: string[]) {
  const allowed = [...new Set(packages.filter((name) => !name.startsWith("!")))].sort();
  const denied = [
    ...new Set(packages.filter((name) => name.startsWith("!")).map((name) => name.slice(1))),
  ]
    .filter((name) => !allowed.includes(name))
    .sort();
  const entries = [
    ...allowed.map((name) => ({ name, allow: true })),
    ...denied.map((name) => ({ name, allow: false })),
  ].sort((a, b) => a.name.localeCompare(b.name));
  return `${PNPM_WORKSPACE_HEADER} — regenerated by \`pnpm site sync\`; installed modules add entries.
# Which dependencies may run install scripts (native binaries).
allowBuilds:
${entries.map(({ name, allow }) => `  "${name}": ${allow}`).join("\n")}
onlyBuiltDependencies:
${allowed.map((name) => `  - "${name}"`).join("\n")}
`;
}

/** Installed modules in dependency order (manifest keys are kept in install order). */
export function orderedModules(manifest: ProjectManifest): ModuleManifest[] {
  const all = manifest.modules;
  const ordered: ModuleManifest[] = [];
  const seen = new Set<string>();
  const visit = (name: string) => {
    if (seen.has(name) || !all[name]) return;
    seen.add(name);
    all[name].requires.forEach(visit);
    ordered.push(all[name]);
  };
  Object.keys(all).forEach(visit);
  return ordered;
}

async function appendGitignore(projectDir: string, lines: string[]) {
  if (lines.length === 0) return;
  const file = path.join(projectDir, ".gitignore");
  const current = (await readTextIfExists(file)) ?? "";
  const missing = lines.filter((line) => !current.split("\n").includes(line));
  if (missing.length === 0) return;
  await writeText(file, `${current.replace(/\n*$/, "\n")}\n${missing.join("\n")}\n`);
}

export type ApplyOptions = {
  registry: Registry;
  projectDir: string;
  manifest: ProjectManifest;
  plan: Plan;
  /** Items whose files should be copied (usually plan.added). */
  selection: Selection;
  preset?: Preset | null;
  overwrite?: boolean;
  /** Extra site.config.ts changes (create-time values). */
  siteConfig?: SiteConfigChanges;
};

export async function applyPlan(options: ApplyOptions): Promise<ApplyResult> {
  const {
    registry,
    projectDir,
    manifest,
    plan,
    selection,
    preset = null,
    overwrite = false,
  } = options;
  const result: ApplyResult = {
    written: [],
    skipped: [],
    dependencies: [],
    touched: [],
    postInstall: [],
  };

  // 1. Files
  for (const job of itemJobs(registry, plan, selection, preset)) {
    const outcome = await copyFile(registry, projectDir, manifest, job, overwrite);
    if (outcome.status === "written") result.written.push(job.entry.to);
    if (outcome.status === "skipped")
      result.skipped.push({ path: job.entry.to, reason: outcome.reason });
  }

  // Module docs travel with the code, so every project documents itself.
  for (const m of plan.modules.filter((m) => selection.modules.includes(m.name))) {
    const readme = await readTextIfExists(
      path.join(registry.root, "registry", "modules", m.name, "README.md"),
    );
    if (readme) await writeText(path.join(projectDir, ".site", "modules", `${m.name}.md`), readme);
  }

  // 2. Record snapshots before generating (generation reads the manifest).
  const addedModules = plan.modules.filter((m) => selection.modules.includes(m.name));
  for (const m of plan.modules)
    if (selection.modules.includes(m.name)) manifest.modules[m.name] = m;
  for (const s of plan.sections)
    if (selection.sections.includes(s.name)) manifest.sections[s.name] = s;
  for (const u of plan.ui) if (selection.ui.includes(u.name)) manifest.ui[u.name] = u;
  // Keep module keys in dependency order for readability.
  manifest.modules = Object.fromEntries(
    plan.modules.map((m) => [m.name, manifest.modules[m.name] ?? m]),
  );

  // 3. package.json
  const dependencies: Record<string, string> = {};
  const devDependencies: Record<string, string> = {};
  const scripts: Record<string, string> = {};
  const items = [
    ...plan.ui.filter((u) => selection.ui.includes(u.name)),
    ...plan.sections.filter((s) => selection.sections.includes(s.name)),
    ...addedModules,
  ];
  for (const item of items) Object.assign(dependencies, item.dependencies);
  for (const m of addedModules) {
    Object.assign(devDependencies, m.devDependencies);
    Object.assign(scripts, m.contributes.scripts);
  }
  const merged = mergePackageJson(await readPackageJson(projectDir), {
    dependencies,
    devDependencies,
    scripts,
  });
  await writePackageJson(projectDir, merged.pkg);
  result.dependencies = merged.added;

  // 4. site.config.ts
  const configChanges: SiteConfigChanges = {
    ...options.siteConfig,
    nav: [...(options.siteConfig?.nav ?? []), ...addedModules.flatMap((m) => m.contributes.nav)],
    blocks: Object.assign({}, ...addedModules.map((m) => m.contributes.siteConfig)),
    features: Object.assign({}, ...addedModules.map((m) => m.contributes.features)),
    merge:
      preset?.siteConfig && Object.keys(preset.siteConfig).length ? preset.siteConfig : undefined,
  };
  const configFile = path.join(projectDir, "site.config.ts");
  const configCode = await readTextIfExists(configFile);
  if (configCode !== null) {
    try {
      const next = updateSiteConfig(configCode, configChanges);
      if (next !== configCode) {
        await writeText(configFile, next);
        result.touched.push("site.config.ts");
      }
    } catch (error) {
      const lines = describeChanges(configChanges);
      log.warn(`${(error as Error).message}${lines.length ? `\n  ${lines.join("\n  ")}` : ""}`);
    }
  }

  // 5. .gitignore
  await appendGitignore(
    projectDir,
    addedModules.flatMap((m) => m.contributes.gitignore),
  );

  // 6. README modules table
  const readmeFile = path.join(projectDir, "README.md");
  const readme = await readTextIfExists(readmeFile);
  if (readme !== null) {
    const next = updateReadme(readme, orderedModules(manifest));
    if (next !== readme) await writeText(readmeFile, next);
  }

  // 7. Generated files + manifest
  manifest.core = {
    version: registry.core.version,
    slots: registry.core.slots,
    env: registry.core.env,
    allowBuilds: registry.core.allowBuilds,
  };
  result.touched.push(...(await syncGenerated(projectDir, manifest)));
  await writeManifest(projectDir, manifest);

  result.postInstall = addedModules
    .filter((m) => m.postInstall.length > 0)
    .map((m) => ({ module: m.name, notes: m.postInstall }));
  return result;
}
