/**
 * Generates presets with the local CLI and proves each one is shippable:
 * install → typecheck → lint → production build, exactly as a new user would.
 *
 *   pnpm build:preset saas             # one preset
 *   pnpm build:preset                  # all presets, one after another
 *   pnpm build:preset blog --keep      # keep the generated project for inspection
 *   pnpm build:preset starter          # the bare starter, no preset
 *
 * Projects are created in the OS temp directory, outside this workspace, so
 * nothing from the monorepo leaks into them. The CLI is linked from
 * packages/cli (built first if needed).
 */
import { existsSync } from "node:fs";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { x } from "tinyexec";

import { Registry } from "../packages/cli/src/registry/registry";

const root = path.resolve(import.meta.dirname, "..");
const args = process.argv.slice(2);
const keep = args.includes("--keep");
const registry = await Registry.load({ root, source: "local", ref: "local", commit: null });
const requested = args.filter((arg) => !arg.startsWith("--"));
/** "starter" = no preset: the bare skeleton must build too. */
const STARTER = "starter";
const names = requested.length ? requested : [STARTER, ...registry.presets.keys()];

for (const name of names) {
  if (name !== STARTER && !registry.presets.has(name)) {
    console.error(
      `Unknown preset "${name}". Available: ${[...registry.presets.keys()].join(", ")}`,
    );
    process.exit(1);
  }
}

async function step(
  label: string,
  command: string,
  commandArgs: string[],
  cwd: string,
  env: NodeJS.ProcessEnv = {},
) {
  const started = Date.now();
  const result = await x(command, commandArgs, {
    nodeOptions: { cwd, env: { ...process.env, ...env } },
    throwOnError: false,
  });
  const seconds = ((Date.now() - started) / 1000).toFixed(1);
  if (result.exitCode !== 0) {
    console.error(`  ✖ ${label} (${seconds}s)\n`);
    console.error((result.stdout + result.stderr).trim().split("\n").slice(-60).join("\n"));
    return false;
  }
  console.log(`  ✔ ${label} (${seconds}s)`);
  return true;
}

const cliDir = path.join(root, "packages/cli");
if (!existsSync(path.join(cliDir, "dist/site.mjs"))) {
  const ok = await step(
    "build CLI",
    "pnpm",
    ["--filter", "@site-forge/create-site", "build"],
    root,
  );
  if (!ok) process.exit(1);
}

const failed: string[] = [];
for (const name of names) {
  const preset = registry.presets.get(name) ?? { title: "Starter", modules: [], theme: "neutral" };
  console.log(
    `\n${preset.title} (${name}): ${preset.modules.length} modules, theme ${preset.theme}`,
  );
  const tmp = await mkdtemp(path.join(os.tmpdir(), `site-forge-${name}-`));
  const dir = path.join(tmp, name);

  const ok =
    (await step(
      "create",
      path.join(root, "node_modules/.bin/tsx"),
      [
        path.join(cliDir, "src/bin/create-site.ts"),
        dir,
        ...(name === STARTER ? [] : ["--preset", name]),
        "--yes",
        "--no-install",
        "--no-git",
        "--name",
        `${preset.title} Test`,
        "--description",
        `A ${preset.title.toLowerCase()} generated by the preset build check.`,
        "--url",
        "https://example.com",
        "--author",
        "Preset Check",
        "--cli-spec",
        `link:${cliDir}`,
        "--pm",
        "pnpm",
      ],
      root,
      { SITE_FORGE_PATH: root, CI: "1" },
    )) &&
    (await step("install", "pnpm", ["install"], dir)) &&
    (await step("typecheck", "pnpm", ["typecheck"], dir)) &&
    (await step("lint", "pnpm", ["lint"], dir)) &&
    (await step("build", "pnpm", ["build"], dir, {
      SKIP_ENV_VALIDATION: "1",
      NEXT_TELEMETRY_DISABLED: "1",
    }));

  if (!ok) failed.push(name);
  if (keep || !ok) console.log(`  → ${dir}`);
  else await rm(tmp, { recursive: true, force: true });
}

if (failed.length) {
  console.error(`\n✖ ${failed.length} preset(s) failed: ${failed.join(", ")}`);
  process.exit(1);
}
console.log(`\n✔ ${names.length} preset(s) build cleanly`);
