/**
 * Writes docs/catalog.md from the registry manifests, so the list of modules,
 * sections, primitives, presets and themes can never drift from the code.
 *
 *   pnpm docs:catalog           # regenerate
 *   pnpm docs:catalog --check   # fail if it's out of date (CI)
 */
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { Registry } from "../packages/cli/src/registry/registry";

const root = path.resolve(import.meta.dirname, "..");
const registry = await Registry.load({ root, source: "local", ref: "local", commit: null });
const out = path.join(root, "docs/catalog.md");

const CATEGORY_TITLES: Record<string, string> = {
  "seo-ops": "SEO & operations",
  content: "Content",
  marketing: "Marketing",
  saas: "SaaS",
  portfolio: "Portfolio & personal",
  commerce: "Commerce",
  infrastructure: "Infrastructure",
  developer: "Developer",
};

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (items: string[]) => items.map((item) => `\`${item}\``).join(", ");

const lines: string[] = [
  "# Catalog",
  "",
  "<!-- Generated by `pnpm docs:catalog` from the registry manifests. Do not edit. -->",
  "",
  `${registry.modules.size} modules · ${registry.sections.size} sections · ${registry.ui.size} UI primitives · ${registry.presets.size} presets · ${registry.themes.size} themes`,
  "",
  "Add anything below to a project with `pnpm site add <name>` (sections as `section:<name>`,",
  "primitives as `ui:<name>`). Each module's README is copied into the project at",
  "`.site/modules/<name>.md`.",
  "",
  "## Presets",
  "",
  "| Preset | What you get | Modules | Theme |",
  "| ------ | ------------ | ------- | ----- |",
  ...[...registry.presets.values()].map(
    (p) => `| \`${p.name}\` | ${cell(p.description)} | ${code(p.modules)} | ${p.theme} |`,
  ),
  "",
  "`pnpm dlx @site-forge/create-site my-site --preset <name>`",
  "",
  "## Modules",
];

const byCategory = new Map<
  string,
  typeof registry.modules extends Map<string, infer M> ? M[] : never
>();
for (const m of registry.modules.values())
  byCategory.set(m.category, [...(byCategory.get(m.category) ?? []), m]);
for (const [category, title] of Object.entries(CATEGORY_TITLES)) {
  const modules = byCategory.get(category);
  if (!modules?.length) continue;
  lines.push(
    "",
    `### ${title}`,
    "",
    "| Module | Description | Requires | Env | Routes |",
    "| ------ | ----------- | -------- | --- | ------ |",
  );
  for (const m of modules.sort((a, b) => a.name.localeCompare(b.name))) {
    const required = m.env.filter((e) => e.required).length;
    const env = m.env.length ? `${m.env.length}${required ? ` (${required} in prod)` : ""}` : "–";
    lines.push(
      `| [\`${m.name}\`](../registry/modules/${m.name}/README.md) | ${cell(m.description)} | ${m.requires.length ? code(m.requires) : "–"} | ${env} | ${m.routes.length ? code(m.routes) : "–"} |`,
    );
  }
}

lines.push(
  "",
  "## Sections",
  "",
  "| Section | Group | Description |",
  "| ------- | ----- | ----------- |",
);
for (const s of [...registry.sections.values()].sort(
  (a, b) => a.group.localeCompare(b.group) || a.name.localeCompare(b.name),
)) {
  lines.push(`| \`${s.name}\` | ${s.group} | ${cell(s.description)} |`);
}

lines.push(
  "",
  "## UI primitives",
  "",
  "| Primitive | Description |",
  "| --------- | ----------- |",
);
for (const u of [...registry.ui.values()].sort((a, b) => a.name.localeCompare(b.name))) {
  lines.push(`| \`${u.name}\` | ${cell(u.description)} |`);
}

lines.push("", "## Themes", "", "| Theme | Description |", "| ----- | ----------- |");
for (const t of registry.themes.values()) lines.push(`| \`${t.name}\` | ${cell(t.description)} |`);
lines.push(
  "",
  "Switch with `pnpm site theme <name>`, or tune the dials in `/lab` (theme-lab module).",
  "",
);

const next = lines.join("\n");
if (process.argv.includes("--check")) {
  const current = await readFile(out, "utf8").catch(() => "");
  if (current !== next) {
    console.error("docs/catalog.md is out of date. Run `pnpm docs:catalog`.");
    process.exit(1);
  }
  console.log("✔ docs/catalog.md is up to date");
} else {
  await writeFile(out, next);
  console.log("✔ wrote docs/catalog.md");
}
