// @generated by site-forge — do not edit. Run `pnpm site sync` to regenerate.
// Add variables to a fragment in src/env/ instead; each module owns one.
import { createEnv } from "@t3-oss/env-nextjs";

import { coreEnv } from "./env/core";

export const env = createEnv({
  extends: [coreEnv],
  server: {},
  client: {},
  experimental__runtimeEnv: {},
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
